package com.amanitadesign.steam {
	public final class InputActionOrigin
	{
		// Steam Controller
		public static const None:String = "0";
		public static const SteamController_A:String = "1";
		public static const SteamController_B:String = "2";
		public static const SteamController_X:String = "3";
		public static const SteamController_Y:String = "4";
		public static const SteamController_LeftBumper:String = "5";
		public static const SteamController_RightBumper:String = "6";
		public static const SteamController_LeftGrip:String = "7";
		public static const SteamController_RightGrip:String = "8";
		public static const SteamController_Start:String = "9";
		public static const SteamController_Back:String = "10";
		public static const SteamController_LeftPad_Touch:String = "11";
		public static const SteamController_LeftPad_Swipe:String = "12";
		public static const SteamController_LeftPad_Click:String = "13";
		public static const SteamController_LeftPad_DPadNorth:String = "14";
		public static const SteamController_LeftPad_DPadSouth:String = "15";
		public static const SteamController_LeftPad_DPadWest:String = "16";
		public static const SteamController_LeftPad_DPadEast:String = "17";
		public static const SteamController_RightPad_Touch:String = "18";
		public static const SteamController_RightPad_Swipe:String = "19";
		public static const SteamController_RightPad_Click:String = "20";
		public static const SteamController_RightPad_DPadNorth:String = "21";
		public static const SteamController_RightPad_DPadSouth:String = "22";
		public static const SteamController_RightPad_DPadWest:String = "23";
		public static const SteamController_RightPad_DPadEast:String = "24";
		public static const SteamController_LeftTrigger_Pull:String = "25";
		public static const SteamController_LeftTrigger_Click:String = "26";
		public static const SteamController_RightTrigger_Pull:String = "27";
		public static const SteamController_RightTrigger_Click:String = "28";
		public static const SteamController_LeftStick_Move:String = "29";
		public static const SteamController_LeftStick_Click:String = "30";
		public static const SteamController_LeftStick_DPadNorth:String = "31";
		public static const SteamController_LeftStick_DPadSouth:String = "32";
		public static const SteamController_LeftStick_DPadWest:String = "33";
		public static const SteamController_LeftStick_DPadEast:String = "34";
		public static const SteamController_Gyro_Move:String = "35";
		public static const SteamController_Gyro_Pitch:String = "36";
		public static const SteamController_Gyro_Yaw:String = "37";
		public static const SteamController_Gyro_Roll:String = "38";
		public static const SteamController_Reserved0:String = "39";
		public static const SteamController_Reserved1:String = "40";
		public static const SteamController_Reserved2:String = "41";
		public static const SteamController_Reserved3:String = "42";
		public static const SteamController_Reserved4:String = "43";
		public static const SteamController_Reserved5:String = "44";
		public static const SteamController_Reserved6:String = "45";
		public static const SteamController_Reserved7:String = "46";
		public static const SteamController_Reserved8:String = "47";
		public static const SteamController_Reserved9:String = "48";
		public static const SteamController_Reserved10:String = "49";

		// PS4 Dual Shock
		public static const PS4_X:String = "50";
		public static const PS4_Circle:String = "51";
		public static const PS4_Triangle:String = "52";
		public static const PS4_Square:String = "53";
		public static const PS4_LeftBumper:String = "54";
		public static const PS4_RightBumper:String = "55";
		public static const PS4_Options:String = "56";	//Start
		public static const PS4_Share:String = "57";		//Back
		public static const PS4_LeftPad_Touch:String = "58";
		public static const PS4_LeftPad_Swipe:String = "59";
		public static const PS4_LeftPad_Click:String = "60";
		public static const PS4_LeftPad_DPadNorth:String = "61";
		public static const PS4_LeftPad_DPadSouth:String = "62";
		public static const PS4_LeftPad_DPadWest:String = "63";
		public static const PS4_LeftPad_DPadEast:String = "64";
		public static const PS4_RightPad_Touch:String = "65";
		public static const PS4_RightPad_Swipe:String = "66";
		public static const PS4_RightPad_Click:String = "67";
		public static const PS4_RightPad_DPadNorth:String = "68";
		public static const PS4_RightPad_DPadSouth:String = "69";
		public static const PS4_RightPad_DPadWest:String = "70";
		public static const PS4_RightPad_DPadEast:String = "71";
		public static const PS4_CenterPad_Touch:String = "72";
		public static const PS4_CenterPad_Swipe:String = "73";
		public static const PS4_CenterPad_Click:String = "74";
		public static const PS4_CenterPad_DPadNorth:String = "75";
		public static const PS4_CenterPad_DPadSouth:String = "76";
		public static const PS4_CenterPad_DPadWest:String = "77";
		public static const PS4_CenterPad_DPadEast:String = "78";
		public static const PS4_LeftTrigger_Pull:String = "79";
		public static const PS4_LeftTrigger_Click:String = "80";
		public static const PS4_RightTrigger_Pull:String = "81";
		public static const PS4_RightTrigger_Click:String = "82";
		public static const PS4_LeftStick_Move:String = "83";
		public static const PS4_LeftStick_Click:String = "84";
		public static const PS4_LeftStick_DPadNorth:String = "85";
		public static const PS4_LeftStick_DPadSouth:String = "86";
		public static const PS4_LeftStick_DPadWest:String = "87";
		public static const PS4_LeftStick_DPadEast:String = "88";
		public static const PS4_RightStick_Move:String = "89";
		public static const PS4_RightStick_Click:String = "90";
		public static const PS4_RightStick_DPadNorth:String = "91";
		public static const PS4_RightStick_DPadSouth:String = "92";
		public static const PS4_RightStick_DPadWest:String = "93";
		public static const PS4_RightStick_DPadEast:String = "94";
		public static const PS4_DPad_North:String = "95";
		public static const PS4_DPad_South:String = "96";
		public static const PS4_DPad_West:String = "97";
		public static const PS4_DPad_East:String = "98";
		public static const PS4_Gyro_Move:String = "99";
		public static const PS4_Gyro_Pitch:String = "100";
		public static const PS4_Gyro_Yaw:String = "101";
		public static const PS4_Gyro_Roll:String = "102";
		public static const PS4_DPad_Move:String = "103";
		public static const PS4_Reserved1:String = "104";
		public static const PS4_Reserved2:String = "105";
		public static const PS4_Reserved3:String = "106";
		public static const PS4_Reserved4:String = "107";
		public static const PS4_Reserved5:String = "108";
		public static const PS4_Reserved6:String = "109";
		public static const PS4_Reserved7:String = "110";
		public static const PS4_Reserved8:String = "111";
		public static const PS4_Reserved9:String = "112";
		public static const PS4_Reserved10:String = "113";

		// XBox One
		public static const XBoxOne_A:String = "114";
		public static const XBoxOne_B:String = "115";
		public static const XBoxOne_X:String = "116";
		public static const XBoxOne_Y:String = "117";
		public static const XBoxOne_LeftBumper:String = "118";
		public static const XBoxOne_RightBumper:String = "119";
		public static const XBoxOne_Menu:String = "120";  //Start
		public static const XBoxOne_View:String = "121";  //Back
		public static const XBoxOne_LeftTrigger_Pull:String = "122";
		public static const XBoxOne_LeftTrigger_Click:String = "123";
		public static const XBoxOne_RightTrigger_Pull:String = "124";
		public static const XBoxOne_RightTrigger_Click:String = "125";
		public static const XBoxOne_LeftStick_Move:String = "126";
		public static const XBoxOne_LeftStick_Click:String = "127";
		public static const XBoxOne_LeftStick_DPadNorth:String = "128";
		public static const XBoxOne_LeftStick_DPadSouth:String = "129";
		public static const XBoxOne_LeftStick_DPadWest:String = "130";
		public static const XBoxOne_LeftStick_DPadEast:String = "131";
		public static const XBoxOne_RightStick_Move:String = "132";
		public static const XBoxOne_RightStick_Click:String = "133";
		public static const XBoxOne_RightStick_DPadNorth:String = "134";
		public static const XBoxOne_RightStick_DPadSouth:String = "135";
		public static const XBoxOne_RightStick_DPadWest:String = "136";
		public static const XBoxOne_RightStick_DPadEast:String = "137";
		public static const XBoxOne_DPad_North:String = "138";
		public static const XBoxOne_DPad_South:String = "139";
		public static const XBoxOne_DPad_West:String = "140";
		public static const XBoxOne_DPad_East:String = "141";
		public static const XBoxOne_DPad_Move:String = "142";
		public static const XBoxOne_LeftGrip_Lower:String = "143";
		public static const XBoxOne_LeftGrip_Upper:String = "144";
		public static const XBoxOne_RightGrip_Lower:String = "145";
		public static const XBoxOne_RightGrip_Upper:String = "146";
		public static const XBoxOne_Share:String = "147"; // Xbox Series X controllers only
		public static const XBoxOne_Reserved6:String = "148";
		public static const XBoxOne_Reserved7:String = "149";
		public static const XBoxOne_Reserved8:String = "150";
		public static const XBoxOne_Reserved9:String = "151";
		public static const XBoxOne_Reserved10:String = "152";
		
		// XBox 360
		public static const XBox360_A:String = "153";
		public static const XBox360_B:String = "154";
		public static const XBox360_X:String = "155";
		public static const XBox360_Y:String = "156";
		public static const XBox360_LeftBumper:String = "157";
		public static const XBox360_RightBumper:String = "158";
		public static const XBox360_Start:String = "159";		//Start
		public static const XBox360_Back:String = "160";		//Back
		public static const XBox360_LeftTrigger_Pull:String = "161";
		public static const XBox360_LeftTrigger_Click:String = "162";
		public static const XBox360_RightTrigger_Pull:String = "163";
		public static const XBox360_RightTrigger_Click:String = "164";
		public static const XBox360_LeftStick_Move:String = "165";
		public static const XBox360_LeftStick_Click:String = "166";
		public static const XBox360_LeftStick_DPadNorth:String = "167";
		public static const XBox360_LeftStick_DPadSouth:String = "168";
		public static const XBox360_LeftStick_DPadWest:String = "169";
		public static const XBox360_LeftStick_DPadEast:String = "170";
		public static const XBox360_RightStick_Move:String = "171";
		public static const XBox360_RightStick_Click:String = "172";
		public static const XBox360_RightStick_DPadNorth:String = "173";
		public static const XBox360_RightStick_DPadSouth:String = "174";
		public static const XBox360_RightStick_DPadWest:String = "175";
		public static const XBox360_RightStick_DPadEast:String = "176";
		public static const XBox360_DPad_North:String = "177";
		public static const XBox360_DPad_South:String = "178";
		public static const XBox360_DPad_West:String = "179";
		public static const XBox360_DPad_East:String = "180";	
		public static const XBox360_DPad_Move:String = "181";
		public static const XBox360_Reserved1:String = "182";
		public static const XBox360_Reserved2:String = "183";
		public static const XBox360_Reserved3:String = "184";
		public static const XBox360_Reserved4:String = "185";
		public static const XBox360_Reserved5:String = "186";
		public static const XBox360_Reserved6:String = "187";
		public static const XBox360_Reserved7:String = "188";
		public static const XBox360_Reserved8:String = "189";
		public static const XBox360_Reserved9:String = "190";
		public static const XBox360_Reserved10:String = "191";

		// Switch - Pro or Joycons used as a single input device.
		// This does not apply to a single joycon
		public static const Switch_A:String = "192";
		public static const Switch_B:String = "193";
		public static const Switch_X:String = "194";
		public static const Switch_Y:String = "195";
		public static const Switch_LeftBumper:String = "196";
		public static const Switch_RightBumper:String = "197";
		public static const Switch_Plus:String = "198";	//Start
		public static const Switch_Minus:String = "199";	//Back
		public static const Switch_Capture:String = "200";
		public static const Switch_LeftTrigger_Pull:String = "201";
		public static const Switch_LeftTrigger_Click:String = "202";
		public static const Switch_RightTrigger_Pull:String = "203";
		public static const Switch_RightTrigger_Click:String = "204";
		public static const Switch_LeftStick_Move:String = "205";
		public static const Switch_LeftStick_Click:String = "206";
		public static const Switch_LeftStick_DPadNorth:String = "207";
		public static const Switch_LeftStick_DPadSouth:String = "208";
		public static const Switch_LeftStick_DPadWest:String = "209";
		public static const Switch_LeftStick_DPadEast:String = "210";
		public static const Switch_RightStick_Move:String = "211";
		public static const Switch_RightStick_Click:String = "212";
		public static const Switch_RightStick_DPadNorth:String = "213";
		public static const Switch_RightStick_DPadSouth:String = "214";
		public static const Switch_RightStick_DPadWest:String = "215";
		public static const Switch_RightStick_DPadEast:String = "216";
		public static const Switch_DPad_North:String = "217";
		public static const Switch_DPad_South:String = "218";
		public static const Switch_DPad_West:String = "219";
		public static const Switch_DPad_East:String = "220";
		public static const Switch_ProGyro_Move:String = "221";  // Primary Gyro in Pro Controller:String = "222"; or Right JoyCon
		public static const Switch_ProGyro_Pitch:String = "223";  // Primary Gyro in Pro Controller:String = "224"; or Right JoyCon
		public static const Switch_ProGyro_Yaw:String = "225";  // Primary Gyro in Pro Controller:String = "226"; or Right JoyCon
		public static const Switch_ProGyro_Roll:String = "227";  // Primary Gyro in Pro Controller:String = "228"; or Right JoyCon
		public static const Switch_DPad_Move:String = "229";
		public static const Switch_Reserved1:String = "230";
		public static const Switch_Reserved2:String = "231";
		public static const Switch_Reserved3:String = "232";
		public static const Switch_Reserved4:String = "233";
		public static const Switch_Reserved5:String = "234";
		public static const Switch_Reserved6:String = "235";
		public static const Switch_Reserved7:String = "236";
		public static const Switch_Reserved8:String = "237";
		public static const Switch_Reserved9:String = "238";
		public static const Switch_Reserved10:String = "239";

		// Switch JoyCon Specific
		public static const Switch_RightGyro_Move:String = "240";  // Right JoyCon Gyro generally should correspond to Pro's single gyro
		public static const Switch_RightGyro_Pitch:String = "241";  // Right JoyCon Gyro generally should correspond to Pro's single gyro
		public static const Switch_RightGyro_Yaw:String = "242";  // Right JoyCon Gyro generally should correspond to Pro's single gyro
		public static const Switch_RightGyro_Roll:String = "243";  // Right JoyCon Gyro generally should correspond to Pro's single gyro
		public static const Switch_LeftGyro_Move:String = "244";
		public static const Switch_LeftGyro_Pitch:String = "245";
		public static const Switch_LeftGyro_Yaw:String = "246";
		public static const Switch_LeftGyro_Roll:String = "247";
		public static const Switch_LeftGrip_Lower:String = "248"; // Left JoyCon SR Button
		public static const Switch_LeftGrip_Upper:String = "249"; // Left JoyCon SL Button
		public static const Switch_RightGrip_Lower:String = "250";  // Right JoyCon SL Button
		public static const Switch_RightGrip_Upper:String = "251";  // Right JoyCon SR Button
		public static const Switch_JoyConButton_N:String = "252"; // With a Horizontal JoyCon this will be Y or what would be Dpad Right when vertical
		public static const Switch_JoyConButton_E:String = "253"; // X
		public static const Switch_JoyConButton_S:String = "254"; // A
		public static const Switch_JoyConButton_W:String = "255"; // B
		public static const Switch_Reserved15:String = "256";
		public static const Switch_Reserved16:String = "257";
		public static const Switch_Reserved17:String = "258";
		public static const Switch_Reserved18:String = "259";
		public static const Switch_Reserved19:String = "260";
		public static const Switch_Reserved20:String = "261";

		// Added in SDK 1.51
		public static const PS5_X:String = "262";
		public static const PS5_Circle:String = "263";
		public static const PS5_Triangle:String = "264";
		public static const PS5_Square:String = "265";
		public static const PS5_LeftBumper:String = "266";
		public static const PS5_RightBumper:String = "267";
		public static const PS5_Option:String = "268";	//Start
		public static const PS5_Create:String = "269";		//Back
		public static const PS5_Mute:String = "270";
		public static const PS5_LeftPad_Touch:String = "271";
		public static const PS5_LeftPad_Swipe:String = "272";
		public static const PS5_LeftPad_Click:String = "273";
		public static const PS5_LeftPad_DPadNorth:String = "274";
		public static const PS5_LeftPad_DPadSouth:String = "275";
		public static const PS5_LeftPad_DPadWest:String = "276";
		public static const PS5_LeftPad_DPadEast:String = "277";
		public static const PS5_RightPad_Touch:String = "278";
		public static const PS5_RightPad_Swipe:String = "279";
		public static const PS5_RightPad_Click:String = "280";
		public static const PS5_RightPad_DPadNorth:String = "281";
		public static const PS5_RightPad_DPadSouth:String = "282";
		public static const PS5_RightPad_DPadWest:String = "283";
		public static const PS5_RightPad_DPadEast:String = "284";
		public static const PS5_CenterPad_Touch:String = "285";
		public static const PS5_CenterPad_Swipe:String = "286";
		public static const PS5_CenterPad_Click:String = "287";
		public static const PS5_CenterPad_DPadNorth:String = "288";
		public static const PS5_CenterPad_DPadSouth:String = "289";
		public static const PS5_CenterPad_DPadWest:String = "290";
		public static const PS5_CenterPad_DPadEast:String = "291";
		public static const PS5_LeftTrigger_Pull:String = "292";
		public static const PS5_LeftTrigger_Click:String = "293";
		public static const PS5_RightTrigger_Pull:String = "294";
		public static const PS5_RightTrigger_Click:String = "295";
		public static const PS5_LeftStick_Move:String = "296";
		public static const PS5_LeftStick_Click:String = "297";
		public static const PS5_LeftStick_DPadNorth:String = "298";
		public static const PS5_LeftStick_DPadSouth:String = "299";
		public static const PS5_LeftStick_DPadWest:String = "300";
		public static const PS5_LeftStick_DPadEast:String = "301";
		public static const PS5_RightStick_Move:String = "302";
		public static const PS5_RightStick_Click:String = "303";
		public static const PS5_RightStick_DPadNorth:String = "304";
		public static const PS5_RightStick_DPadSouth:String = "305";
		public static const PS5_RightStick_DPadWest:String = "306";
		public static const PS5_RightStick_DPadEast:String = "307";
		public static const PS5_DPad_North:String = "308";
		public static const PS5_DPad_South:String = "309";
		public static const PS5_DPad_West:String = "310";
		public static const PS5_DPad_East:String = "311";
		public static const PS5_Gyro_Move:String = "312";
		public static const PS5_Gyro_Pitch:String = "313";
		public static const PS5_Gyro_Yaw:String = "314";
		public static const PS5_Gyro_Roll:String = "315";
		public static const PS5_DPad_Move:String = "316";
		public static const PS5_LeftGrip:String = "317";
		public static const PS5_RightGrip:String = "318";
		public static const PS5_LeftFn:String = "319";
		public static const PS5_RightFn:String = "320";
		public static const PS5_Reserved5:String = "321";
		public static const PS5_Reserved6:String = "322";
		public static const PS5_Reserved7:String = "323";
		public static const PS5_Reserved8:String = "324";
		public static const PS5_Reserved9:String = "325";
		public static const PS5_Reserved10:String = "326";
		public static const PS5_Reserved11:String = "327";
		public static const PS5_Reserved12:String = "328";
		public static const PS5_Reserved13:String = "329";
		public static const PS5_Reserved14:String = "330";
		public static const PS5_Reserved15:String = "331";
		public static const PS5_Reserved16:String = "332";
		public static const PS5_Reserved17:String = "333";
		public static const PS5_Reserved18:String = "334";
		public static const PS5_Reserved19:String = "335";
		public static const PS5_Reserved20:String = "336";

		// Added in SDK 1.53
		public static const SteamDeck_A:String = "337";
		public static const SteamDeck_B:String = "338";
		public static const SteamDeck_X:String = "339";
		public static const SteamDeck_Y:String = "340";
		public static const SteamDeck_L1:String = "341";
		public static const SteamDeck_R1:String = "342";
		public static const SteamDeck_Menu:String = "343";
		public static const SteamDeck_View:String = "344";
		public static const SteamDeck_LeftPad_Touch:String = "345";
		public static const SteamDeck_LeftPad_Swipe:String = "346";
		public static const SteamDeck_LeftPad_Click:String = "347";
		public static const SteamDeck_LeftPad_DPadNorth:String = "348";
		public static const SteamDeck_LeftPad_DPadSouth:String = "349";
		public static const SteamDeck_LeftPad_DPadWest:String = "350";
		public static const SteamDeck_LeftPad_DPadEast:String = "351";
		public static const SteamDeck_RightPad_Touch:String = "352";
		public static const SteamDeck_RightPad_Swipe:String = "353";
		public static const SteamDeck_RightPad_Click:String = "354";
		public static const SteamDeck_RightPad_DPadNorth:String = "355";
		public static const SteamDeck_RightPad_DPadSouth:String = "356";
		public static const SteamDeck_RightPad_DPadWest:String = "357";
		public static const SteamDeck_RightPad_DPadEast:String = "358";
		public static const SteamDeck_L2_SoftPull:String = "359";
		public static const SteamDeck_L2:String = "360";
		public static const SteamDeck_R2_SoftPull:String = "361";
		public static const SteamDeck_R2:String = "362";
		public static const SteamDeck_LeftStick_Move:String = "363";
		public static const SteamDeck_L3:String = "364";
		public static const SteamDeck_LeftStick_DPadNorth:String = "365";
		public static const SteamDeck_LeftStick_DPadSouth:String = "366";
		public static const SteamDeck_LeftStick_DPadWest:String = "367";
		public static const SteamDeck_LeftStick_DPadEast:String = "368";
		public static const SteamDeck_LeftStick_Touch:String = "369";
		public static const SteamDeck_RightStick_Move:String = "370";
		public static const SteamDeck_R3:String = "371";
		public static const SteamDeck_RightStick_DPadNorth:String = "372";
		public static const SteamDeck_RightStick_DPadSouth:String = "373";
		public static const SteamDeck_RightStick_DPadWest:String = "374";
		public static const SteamDeck_RightStick_DPadEast:String = "375";
		public static const SteamDeck_RightStick_Touch:String = "376";
		public static const SteamDeck_L4:String = "377";
		public static const SteamDeck_R4:String = "378";
		public static const SteamDeck_L5:String = "379";
		public static const SteamDeck_R5:String = "380";
		public static const SteamDeck_DPad_Move:String = "381";
		public static const SteamDeck_DPad_North:String = "382";
		public static const SteamDeck_DPad_South:String = "383";
		public static const SteamDeck_DPad_West:String = "384";
		public static const SteamDeck_DPad_East:String = "385";
		public static const SteamDeck_Gyro_Move:String = "386";
		public static const SteamDeck_Gyro_Pitch:String = "387";
		public static const SteamDeck_Gyro_Yaw:String = "388";
		public static const SteamDeck_Gyro_Roll:String = "389";
		public static const SteamDeck_Reserved1:String = "390";
		public static const SteamDeck_Reserved2:String = "391";
		public static const SteamDeck_Reserved3:String = "392";
		public static const SteamDeck_Reserved4:String = "393";
		public static const SteamDeck_Reserved5:String = "394";
		public static const SteamDeck_Reserved6:String = "395";
		public static const SteamDeck_Reserved7:String = "396";
		public static const SteamDeck_Reserved8:String = "397";
		public static const SteamDeck_Reserved9:String = "398";
		public static const SteamDeck_Reserved10:String = "399";
		public static const SteamDeck_Reserved11:String = "400";
		public static const SteamDeck_Reserved12:String = "401";
		public static const SteamDeck_Reserved13:String = "402";
		public static const SteamDeck_Reserved14:String = "403";
		public static const SteamDeck_Reserved15:String = "404";
		public static const SteamDeck_Reserved16:String = "405";
		public static const SteamDeck_Reserved17:String = "406";
		public static const SteamDeck_Reserved18:String = "407";
		public static const SteamDeck_Reserved19:String = "408";
		public static const SteamDeck_Reserved20:String = "409";

		public static const Horipad_M1:String = "410";
		public static const Horipad_M2:String = "411";
		public static const Horipad_L4:String = "412";
		public static const Horipad_R4:String = "413";
		
		public static const Count:String = "414"; // If Steam has added support for new controllers origins will go here.
		public static const MaximumPossibleValue:String = "32767"; // Origins are currently a maximum of 16 bits.
	}
}
